server:
  port: 8080
grpc:
  server:
    port: 9090
    security:
      enabled: false
spring:
  application:
    name: ethereum_balance
ethereum:
  node:
    url: "https://mainnet.infura.io/v3/533e2b5e47ff423396cef0f988195723"