apiVersion: v1
kind: Service
metadata:
  name: ethereum-service
spec:
  type: LoadBalancer
  selector:
    app: ethereum-balance
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
      name: rest
    - port: 9090
      targetPort: 9090
      nodePort: 32000
      name: grpc